// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.SaoLei
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public class GameStartUIPanelData : QFramework.UIPanelData
    {
    }
    
    public partial class GameStartUIPanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as GameStartUIPanelData ?? new GameStartUIPanelData();
            // please add init code here
            GameStartCustomTrans.gameObject.SetActive(false);
            GameStartEasyBtn.onClick.AddListener(OnClickEasyBtn); 
            GameStartNormalBtn.onClick.AddListener(OnClickNormalBtn);
            GameStartHardBtn.onClick.AddListener(OnClickHardBtn);
            GameStartCustomBtn.onClick.AddListener(OnClickCustomBtn);
            GameStartCustonCancelBtn.onClick.AddListener(OnClickCustomCancelBtn);
            GameStartCustonConfirmBtn.onClick.AddListener(OnClickCustomConfirmBtn);
           
        }
        void OnClickEasyBtn()
        {
            StartGame(10);
        }
         void OnClickNormalBtn()
        {
            
            StartGame(20);
        }
         void OnClickHardBtn()
        {
            StartGame(40);
        }
         void OnClickCustomBtn()
        {
            GameStartCustomTrans.gameObject.SetActive(true);
            GameStartCustomInPut.text = "";
        }

        void OnClickCustomConfirmBtn()
        {
            if(GameStartCustomInPut.text!="")
                StartGame(int.Parse(GameStartCustomInPut.text));
        }

        void OnClickCustomCancelBtn()
        {
            GameStartCustomTrans.gameObject.SetActive(false);
            GameStartCustomInPut.text = "";
        }

        void StartGame(int number)
        {
             UIKit.OpenPanel<GameMainUIPanel>(new GameMainUIPanelData(){
                mineNumber = number
            });
            CloseSelf();
        }
        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }
        
        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
