// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.SaoLei
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:461ed575-5db3-4506-a396-5f13fa8d9ebd
    public partial class GameMainUIPanel
    {
        
        public const string NAME = "GameMainUIPanel";
        
        [SerializeField()]
        public UnityEngine.UI.Text GameMainScoreText;
        
        [SerializeField()]
        public UnityEngine.RectTransform GameMainPlayTrans;
        
        private GameMainUIPanelData mPrivateData = null;
        
        public GameMainUIPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new GameMainUIPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            GameMainScoreText = null;
            GameMainPlayTrans = null;
            mData = null;
        }
    }
}
