// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QFramework.SaoLei
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:47c3ce11-5762-40f9-9ddf-49b2a7dfe1f4
    public partial class GameStartUIPanel
    {
        
        public const string NAME = "GameStartUIPanel";
        
        [SerializeField()]
        public UnityEngine.RectTransform GameStartSelectTrans;
        
        [SerializeField()]
        public UnityEngine.UI.Button GameStartEasyBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button GameStartNormalBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button GameStartHardBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button GameStartCustomBtn;
        
        [SerializeField()]
        public UnityEngine.RectTransform GameStartCustomTrans;
        
        [SerializeField()]
        public UnityEngine.UI.InputField GameStartCustomInPut;
        
        [SerializeField()]
        public UnityEngine.UI.Button GameStartCustonConfirmBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button GameStartCustonCancelBtn;
        
        private GameStartUIPanelData mPrivateData = null;
        
        public GameStartUIPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new GameStartUIPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            GameStartSelectTrans = null;
            GameStartEasyBtn = null;
            GameStartNormalBtn = null;
            GameStartHardBtn = null;
            GameStartCustomBtn = null;
            GameStartCustomTrans = null;
            GameStartCustomInPut = null;
            GameStartCustonConfirmBtn = null;
            GameStartCustonCancelBtn = null;
            mData = null;
        }
    }
}
